server:
  port: 9191

#eureka:
#  client:
#    register-with-eureka: true  # Разрешить регистрацию в Eureka (по умолчанию true)
#    fetch-registry: true        # Получать список других сервисов из Eureka (по умолчанию true)
#    service-url:
#      defaultZone: http://localhost:8761/eureka


spring:




#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file:./config

  datasource:
    url: jdbc:postgresql://localhost:5432/mappingdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
      show-sql: true          # Опционально, показывает SQL в консоли
      properties:
        hibernate:
          format_sql: true