spring.application.name=user-module
spring.config.import=configserver:http://localhost:8888
server.port=8083

spring.data.redisPort=6379
spring.data.redishost=localhost
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.timeout=5000