spring:
  application:
    name: EmailModule

  kafka:
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5433/userDb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: an.yan2369@gmail.com
    password: oevduprxiajsddeg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
