server:
  port: 8888

eureka:
  client:
    register-with-eureka: true  # Разрешить регистрацию в Eureka (по умолчанию true)
    fetch-registry: true        # Получать список других сервисов из Eureka (по умолчанию true)
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:./config


